version: 2.1
orbs:
  docker: circleci/docker@2.8.2
workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME  
          tag: ouiTest
          docker-password: DOCKER_HUB_PASSWORD
          docker-username: DOCKER_HUB_USERNAME